#define CELL_X 1000
#define CELL_Y 1000

#define NUM_OF_RUNS 1000

#define NUM_OF_SICK 60

#define PROBABILITY_TO_ADD 10
#define YOUTH_RISK_THRESHOLD 15
#define OLD_RISK_THRESHOLD 60

#define MAX_RECOVERY 5

#define NUM_VACINES_PER_DAY 50
#define VACINE_DAY_START 3
